# - id: doi:10.1371/journal.pcbi.1007128
#   type: paper
#   description: Lorem ipsum _dolor_ **sit amet**, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
#   date: 2020-12-4
#   image: https://journals.plos.org/ploscompbiol/article/figure/image?size=inline&id=info:doi/10.1371/journal.pcbi.1007128.g001&rev=2
#   buttons:
#     - type: manubot
#       link: https://greenelab.github.io/meta-review/
#     - type: source
#       text: Manuscript Source
#       link: https://github.com/greenelab/meta-review
#     - type: website
#       link: http://manubot.org/
#   tags:
#     - open science
#     - collaboration
#   repo: greenelab/meta-review

# - id: doi:10.1016/j.csbj.2020.05.017
#   image: https://ars.els-cdn.com/content/image/1-s2.0-S2001037020302804-gr1.jpg

# - id: doi:10.7554/eLife.32822
#   image: https://iiif.elifesciences.org/lax:32822%2Felife-32822-fig8-v3.tif/full/863,/0/default.webp

- id: doi:10.1109/TAI.2024.3459857
  image: https://www.researchgate.net/publication/384027028/figure/fig1/AS:11431281277961813@1726311551198/The-structure-of-Traffexplainer-consists-of-GNN-based-traffic-prediction-model-and.png
  
- id: doi:10.1109/TAFFC.2024.3396144
  image: https://www.researchgate.net/publication/377949776/figure/fig1/AS:11431281221929808@1706970594720/Model-Architecture.png

- id: doi:10.1007/s10489-023-04767-2
  image: https://link.springer.com/article/10.1007/s10489-023-04767-2/figures/2

- id: doi:10.1093/bib/bbad296
  image: https://oup.silverchair-cdn.com/oup/backfile/Content_public/Journal/bib/24/5/10.1093_bib_bbad296/2/m_bbad296f1.jpeg?Expires=1732442226&Signature=WobzgkuOG7Lr9mY8RxanwJ3yzmR7K09KkAvC-NIuI53wXFHj9vdugsE8Vcgcqtw4FOj-VbIn8wH6-fuBlFdB3kVyNQRvP-Jx7ymgrcATaPLZaHPMCN4TOiqZMJy7XxZE777OaTPSeRV5N56MWf5BKb396MW0EhsD4wO~MdLlj2JAkkP0nuqJJp8qtRdp2NgI6Qha86IK08MJDUzWj8mTPv~IGsv5H9pfyUOfXdNxCXGTZWPhVaGCy3bMIbs4ETMD4JLsYx-ifzkm0geizW1WppoxtG5sX46qSQ507aBwFmdsIvBDu-xSMvV~7sJ4oD~hb8O2XbVhBXSgKjk8q8G7jw__&Key-Pair-Id=APKAIE5G5CRDK6RD3PGA

- id: doi:10.1093/bib/bbac018
  image: https://oup.silverchair-cdn.com/oup/backfile/Content_public/Journal/bib/23/2/10.1093_bib_bbac018/1/m_bbac018f1.jpeg?Expires=1732441379&Signature=GGXrTPlJQdLzCMx1v2FD6Ld1dv3BM1OYrVwIUnShKhhfJqdsBXJBymb3WrLgK09wg9AoexgsYY7cnD9gS6H8tWxhDboYchZDOrm3DS3rxr9TXCrR2b1i7O6D3b3aYnjM2y8cqPqN5EI8kCSx2qoqxiUD5Vm49GocUJMHEUBE314ur6ltvqYZ53dy2A~RJ~0GcAPdmDV7Kro08NY6pEilZo1NCuS3gBIAk2s54OQqG2Bt9rS1hbzlWMY2XTWtKHVUPxIqaLH8mV71tNTJh8sPx82BThlHxyRaRmw~lcP-HPYHqG3CDAagHzSEfB6ieIafIT05aaqvE0aetCcH5aKnBQ__&Key-Pair-Id=APKAIE5G5CRDK6RD3PGA

- id: doi:10.1109/TCBB.2021.3061720
  image: https://ieeexplore.ieee.org/mediastore/IEEE/content/media/8857/9852343/9363460/gan1-3061720-large.gif
  